name: Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '15 17 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3) Garante Yarn 1.x
      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      # 4) Instala dependências conforme lockfile
      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      # 5) Debug install (verbose do Yarn)
      - name: Debug install (verbose)
        run: yarn install --verbose

      # 6) Roda testes Cypress sem --verbose, mas com DEBUG para mais logs
      - name: Rodar testes Cypress
        uses: cypress-io/github-action@v6
        env:
          DEBUG: cypress:cli,cypress:server
        with:
          command: yarn test:all

      # 7) Verifica o conteúdo de allure-results
      - name: Verificar resultados do Allure
        run: |
          echo "=== Conteúdo de allure-results ==="
          ls -R allure-results || echo "=> NÃO ENCONTRADO allure-results"

      # 8) Upload dos resultados (inclui subpastas e todos os arquivos)
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/**/*
