name: Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '10 17 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3) Garante que o Yarn 1.x esteja presente
      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      # 4) Instala dependências conforme seu lockfile
      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      # 5) Debug: logs detalhados na instalação
      - name: Debug install (verbose)
        run: yarn install --verbose

      # 6) Roda seus testes (inclui Allure via seu script test:all)
      - name: Rodar testes Cypress
        uses: cypress-io/github-action@v6
        with:
          command: yarn test:all --verbose

      # 7) Coleta os resultados do Allure como artefato
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
