name: Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 9 * * *'
    - cron: '0 12 * * *'
    - cron: '0 14 * * *'
    - cron: '0 16 * * *'
    - cron: '45 10 * * *'
    - cron: '50 10 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Yarn
        run: npm install -g yarn@1.22.22

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Rodar testes Cypress
        run: yarn cypress run --reporter mochawesome --reporter-options reportDir=cypress/logs,overwrite=false,html=false,json=true

      - name: Salvar logs como artefato (em caso de falha)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-logs
          path: cypress/logs
