name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Altere se seu projeto usar outra versão

      - name: Instalar dependências
        run: yarn install

      - name: Rodar testes Cypress
        uses: cypress-io/github-action@v6
        with:
          command: yarn cypress run
